# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pytest workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Java JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
            java-version: '1.8' # The JDK version to make available on the path.
            java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
            architecture: x64 # (x64 or x86) - defaults to x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyspark pytest "dask[complete]" scipy
    - name: Retrieve template test cases
      run: |
        git remote add upstream https://github.com/tgteacher/BigData-LA4.git
        git fetch upstream master
        git checkout upstream/master -- tests
    - name: Test with pytest
      env: 
        PYTHONHASHSEED: 0
        PYTHONPATH: $PWD/answers
      run: |
        PYTHONPATH=$PWD/answers pytest
